# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Machacha' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Machacha
  pod 'GoogleMLKit/TextRecognition', '3.2.0'
  pod 'GoogleMLKit/TextRecognitionKorean', '3.2.0'

  target 'MachachaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MachachaUITests' do
    # Pods for testing
  end

end

target 'Machacha-push' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Machacha-push
  pod 'GoogleMLKit/TextRecognition', '3.2.0'
  pod 'GoogleMLKit/TextRecognitionKorean', '3.2.0'

end
